<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TidalDiscord.Api</AssemblyName>
    <RootNamespace>TidalDiscord.Api</RootNamespace>
  </PropertyGroup>

</Project>
